#!/usr/bin/env bash

if [ ! -d "jsroot" ]
then
 ./scripts/getjsroot
fi

server ()
{
    local port="${1:-8000}";
    open "http://localhost:${port}/";
    python -c 'import SimpleHTTPServer;
map = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;
map[""] = "text/plain";
for key, value in map.items():
	map[key] = value + ";charset=UTF-8";
SimpleHTTPServer.test();' "$port"
}

server